FROM ghcr.io/mysociety/data_common:sha-e9a2b50

# Make an empty project directory so the 'self' setup doesn't fail and scripts can be setup
# Override the .pth created at previous stages to point to where the working directory will land
COPY pyproject.toml poetry.loc[k] /setup/ 
COPY src/data_common/pyproject.toml src/data_common/poetry.loc[k] /setup/src/data_common/
RUN mkdir /setup/src/uk_parl_petitions_scraper \
    && touch /setup/src/uk_parl_petitions_scraper/__init__.py \
    && mkdir --parents /setup/src/data_common/src/data_common \
    && touch /setup/src/data_common/src/data_common/__init__.py \
    && export PATH="/root/.local/bin:$PATH" \
    && cd /setup/ && poetry install \
    && echo "/workspaces/uk_parl_petitions_scraper/src/" > /usr/local/lib/python3.10/site-packages/uk_parl_petitions_scraper.pth \
    && echo "/workspaces/uk_parl_petitions_scraper/src/data_common/src" > /usr/local/lib/python3.10/site-packages/data_common.pth
