services:
  app:
    image: mysociety/uk-parl-petitions-scraper:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/uk_parl_petitions_scraper      
    volumes:
      - ./:/workspaces/uk_parl_petitions_scraper/